[tool.poetry]
name = "bee-better"
version = "0.1.0"
description = ""
authors = ["Rafał Stępień <rafal.stepien@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
